- name: CentOS | Install EPEL repository
  yum:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS'
  tags:
    - epel

- name: RHEL | Install EPEL repository
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_facts.distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_distribution == 'RedHat'
  tags:
    - epel
