dependency:
  name: galaxy
driver:
  name: docker
lint: |
  ansible-lint -x 204,403,502
  yamllint -c molecule/default/yamllint.yml .
platforms:
  - name: repo_epel-test
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-centos7}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
scenario:
  name: default
verifier:
  name: ansible
